// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PicPay.Infra.Data.Data;

#nullable disable

namespace PicPay.Infra.Data.Migrations
{
    [DbContext(typeof(BancoContext))]
    partial class BancoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PicPay.Domain.Models.LojistaModel", b =>
                {
                    b.Property<Guid>("id_lojista")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("cnpj")
                        .HasColumnType("text");

                    b.Property<string>("cpf")
                        .HasColumnType("text");

                    b.Property<string>("email")
                        .HasColumnType("text");

                    b.Property<string>("nomeCompleto")
                        .HasColumnType("text");

                    b.Property<decimal?>("saldo")
                        .HasColumnType("numeric");

                    b.Property<string>("senha")
                        .HasColumnType("text");

                    b.HasKey("id_lojista");

                    b.ToTable("lojistaModels");
                });

            modelBuilder.Entity("PicPay.Domain.Models.TransferenciaModel", b =>
                {
                    b.Property<Guid>("dd")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("autorizacaoExterna")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("dataTransferencia")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("info_destinatario")
                        .HasColumnType("text");

                    b.Property<string>("info_remetente")
                        .HasColumnType("text");

                    b.Property<bool>("sucesso")
                        .HasColumnType("boolean");

                    b.Property<decimal>("valor")
                        .HasColumnType("numeric");

                    b.HasKey("dd");

                    b.ToTable("transferenciaModels");
                });

            modelBuilder.Entity("PicPay.Domain.Models.UsuarioModel", b =>
                {
                    b.Property<Guid>("id_usuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("cpf")
                        .HasColumnType("text");

                    b.Property<string>("email")
                        .HasColumnType("text");

                    b.Property<string>("nomeCompleto")
                        .HasColumnType("text");

                    b.Property<decimal?>("saldo")
                        .HasColumnType("numeric");

                    b.Property<string>("senha")
                        .HasColumnType("text");

                    b.Property<string>("telefone")
                        .HasColumnType("text");

                    b.HasKey("id_usuario");

                    b.ToTable("usuarioModels");
                });
#pragma warning restore 612, 618
        }
    }
}
